name: My First Workflow

on: 
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  hello-devops:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Show system info
        run: |
          echo "Hello DevOps Engineer!"
          echo "Current time: $(date)"
          echo "Running on: $(uname -a)"
